=== apple006/tangyuan2/tangyuan-hbase/src/main/java/org/xson/tangyuan/hbase/schema/service.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://xson.org/schema/tangyuan/hbase/service" targetNamespace="http://xson.org/schema/tangyuan/hbase/service" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="get">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="dsKey" type="xs:string"/>
			<xs:attribute name="struct" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ROW_CELL"/>
						<xs:enumeration value="ROW_OBJECT"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cacheUse" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="scan">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="dsKey" type="xs:string"/>
			<xs:attribute name="struct" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ROW_CELL"/>
						<xs:enumeration value="ROW_OBJECT"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cacheUse" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="put">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="dsKey" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="putBatch">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
				<xs:element ref="if"/>
				<xs:element ref="elseif"/>
				<xs:element ref="else"/>
				<xs:element ref="foreach"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="dsKey" type="xs:string" use="optional"/>
			<xs:attribute name="async" type="xs:boolean" use="optional"/>
		</xs:complexType>
	</xs:element>
	

	
	
	<xs:element name="delete">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="dsKey" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="if">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="if"/>
					<xs:element ref="elseif"/>
					<xs:element ref="else"/>
					<xs:element ref="foreach"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="test" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="elseif">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="if"/>
					<xs:element ref="elseif"/>
					<xs:element ref="else"/>
					<xs:element ref="foreach"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="test" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="else">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="if"/>
					<xs:element ref="elseif"/>
					<xs:element ref="else"/>
					<xs:element ref="foreach"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foreach">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="if"/>
					<xs:element ref="elseif"/>
					<xs:element ref="else"/>
					<xs:element ref="foreach"/>
					<xs:element ref="item"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="collection" type="xs:string" use="required"/>
			<xs:attribute name="index" type="xs:string"/>
			<xs:attribute name="open" type="xs:string"/>
			<xs:attribute name="close" type="xs:string"/>
			<xs:attribute name="separator" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="item">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="if"/>
					<xs:element ref="elseif"/>
					<xs:element ref="else"/>
					<xs:element ref="foreach"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="hbaseServices">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="get"/>
					<xs:element ref="put"/>
					<xs:element ref="putBatch"/>
					<xs:element ref="scan"/>
					<xs:element ref="delete"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="ns" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== apple006/tangyuan2/tangyuan-hbase/src/test/resources/service-hbase.xml
<?xml version="1.0" encoding="UTF-8"?>
<hbaseServices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://xson.org/schema/tangyuan/hbase/service.xsd" ns="hb">
	
	<putBatch id="putb1" dsKey="tb107">
		<foreach collection="{xxx}" index="{i}">
			<item><![CDATA[
			{
				ns: '',
				table: 	"user_table",
				row:	#{xxx[i]},
				family:	{
					addr: {
						sheng: "河南",
						shi: "新乡",
						qu: "牧野区"
					},
					info: {
						name: "daviex",
						age: 182,
						sex: "男"
					}
				}
			}
			]]></item>
		</foreach>
	</putBatch>
	
	<putBatch id="putb2" dsKey="tb107" async="true">
		<foreach collection="{xxx}" index="{i}">
			<item><![CDATA[
			{
				ns: '',
				table: 	"user_table",
				row:	#{xxx[i]},
				family:	{
					addr: {
						sheng: "河南",
						shi: "新乡",
						qu: "牧野区"
					},
					info: {
						name: "daviex",
						age: 182,
						sex: "男"
					}
				}
			}
			]]></item>
		</foreach>
	</putBatch>	

	<get id="get01" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 		"user_table",
			row:		"row1",
			family:		{
				addr: [ "sheng", "shi", "qu"],
				info: []
			},
			cacheBlocks: true
		}
	]]></get>
	<!-- timeRange: 	[1512368376510, 1512368376510], -->
	<get id="get02" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 		"user_table_ver",
			row:		"row1",
			family:		{
				addr: [ "sheng", "shi", "qu"],
				info: []
			}
		}
	]]></get>

	<get id="get03" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 		"user_table",
			row:		#{xxx},
			family:		{
				addr: [ "sheng", "shi", "qu"],
				info: []
			},
			cacheBlocks: true
		}
	]]></get>

	<put id="put01" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 	"user_table",
			row:	#{row},
			family:	{
				addr: {
					sheng: "河南",
					shi: "新乡",
					qu: "牧野区"
				},
				info: {
					name: "daviex",
					age: 182,
					sex: "男"
				}
			},
			durability: ""
		}
	]]></put>

	<delete id="del01" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 	"user_table",
			row:	#{row},
			family:	{
				addr: {},
				info: {}
			},
			durability: "SYNC_WAL"
		}
	]]></delete>
	<delete id="del02" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 	"user_table",
			row:	#{row},
			family:	{
				addr: {
					sheng: {
						timestamp: 123, 
						scope: "all"
					}
				},
				info: {
					timestamp: 150000,
					version: 150000
				}
			},
			durability: ""
		}
	]]></delete>
	<delete id="del03" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 	"user_table",
			row:	#{xxx}
		}
	]]></delete>
			
	<x>
		{
			ns: '',
			table: 	"user_table",
			row:	#{row},
			family:	{
				addr: {
					sheng: {
						timestamp: 123, 
						scope: "all/last"
					}
				},
				info: {
					timestamp: 150000,
					version: 150000
				}
			},
			
			family:	{
				addr: {
					sheng: {}
				},
				info: {}
			},			
			durability: "SYNC_WAL"
		}	
	</x>

	<!-- 搜索 -->
	<scan id="scan01" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 		"user_table",
			pageSize: 	20,
			family:		{
				addr: [ "sheng", "shi", "qu"],
				info: []
			},
			filter: {
				SingleColumnValueFilter: {
					family: "xxx",
					qualifier: "xxx",
					compareOp: ">",
					value: "xxx",
					comparator: 'RegexStringComparator'
				},
				SingleColumnValueExcludeFilter: {
					family: "xxx",
					qualifier: "xxx",
					compareOp: ">",
					value: "xxx",
					comparator: 'RegexStringComparator'
				},				
				ColumnPrefixFilter: {
					prefix: ""
				},
				MultipleColumnPrefixFilter: {
					prefixes: []
				},
				ColumnRangeFilter: {
					minColumn: "",
					maxColumn: ""
				},
				QualifierFilter: {
					compareOp: ">",
					value: "xxx",
					comparator: 'RegexStringComparator'
				},
				RowFilter: {
					compareOp: ">",
					value: "xxx",
					comparator: 'RegexStringComparator'
				},
				ValueFilter: {
					compareOp: ">",
					value: "xxx",
					comparator: 'RegexStringComparator'
				},
				ValueFilter: {},
				InclusiveStopFilter: {
					stopRowKey: ""
				},
				KeyOnlyFilter: {},
				PageFilter: {
					pageSize: 20
				},
				PrefixFilter: {
					prefix: ""
				},
				SkipFilter: {
					compareOp: ">",
					value: "xxx",
					comparator: 'RegexStringComparator'
				},
				TimestampsFilter: {
					timestamps: []
				},
				operator: ""
			}
		}		
	]]></scan>
	
	<scan id="scan02" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 	"user_table",
			pageSize: 20,
			startRowKey: null,
			stopRowKey: null,
			family:		{
				addr: [ "sheng", "shi", "qu"],
				info: []
			}
		}		
	]]></scan>

	<scan id="scan03" dsKey="tb107"><![CDATA[
		{
			ns: '',
			table: 	"user_table_ver",
			pageSize: 20
		}		
	]]></scan>

</hbaseServices>
